### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ScottBrenner** [lob/aws-creds#25]
Hi, cool tool! Been looking for something like this, might like to use it or at least take inspiration from it.

Please add a license so I may do so!

**Comment by ScottBrenner** [comment]
@robinjoseph08 Thoughts?

**Comment by robinjoseph08** [comment]
Hey @ScottBrenner sorry, looks like this slipped through the cracks! Adding a license is definitely on the list of things to do to make this a bit more useable by the public. I'll add a license today!

**Comment by ScottBrenner** [comment]
Thanks!
